ITEMS = {
    "NOTHING"        : {"address": 0x00, "pretty_name": "Nothing"},
    "SWORD_OF_LIFE"  : {"address": 0x01, "pretty_name": "Sword of Life"},
    "PSYCHO_SWORD"   : {"address": 0x02, "pretty_name": "Psycho Sword"},
    "CRITICAL_SWORD" : {"address": 0x03, "pretty_name": "Critical Sword"},
    "LUCKY_BLADE"    : {"address": 0x04, "pretty_name": "Lucky Blade"},
    "ZANTETSU_SWORD" : {"address": 0x05, "pretty_name": "Zantetsu Sword"},
    "SPIRIT_SWORD"   : {"address": 0x06, "pretty_name": "Spirit Sword"},
    "RECOVERY_SWORD" : {"address": 0x07, "pretty_name": "Recovery Sword"},
    "SOUL_BLADE"     : {"address": 0x08, "pretty_name": "Soul Blade"},
    "IRON_ARMOR"     : {"address": 0x09, "pretty_name": "Iron Armor"},
    "ICE_ARMOR"      : {"address": 0x0A, "pretty_name": "Ice Armor"},
    "BUBBLE_ARMOR"   : {"address": 0x0B, "pretty_name": "Bubble Armor"},
    "MAGIC_ARMOR"    : {"address": 0x0C, "pretty_name": "Magic Armor"},
    "MYSTIC_ARMOR"   : {"address": 0x0D, "pretty_name": "Mystic Armor"},
    "LIGHT_ARMOR"    : {"address": 0x0E, "pretty_name": "Light Armor"},
    "ELEMENTAL_MAIL" : {"address": 0x0F, "pretty_name": "Elemental Mail"},
    "SOUL_ARMOR"     : {"address": 0x10, "pretty_name": "Soul Armor"},
    "FLAME_BALL"     : {"address": 0x11, "pretty_name": "Flame Ball"},
    "LIGHT_ARROW"    : {"address": 0x12, "pretty_name": "Light Arrow"},
    "MAGIC_FLARE"    : {"address": 0x13, "pretty_name": "Magic Flare"},
    "ROTATOR"        : {"address": 0x14, "pretty_name": "Rotator"},
    "SPARK_BOMB"     : {"address": 0x15, "pretty_name": "Spark Bomb"},
    "FLAME_PILLAR"   : {"address": 0x16, "pretty_name": "Flame Pillar"},
    "TORNADO"        : {"address": 0x17, "pretty_name": "Tornado"},
    "PHOENIX"        : {"address": 0x18, "pretty_name": "Phoenix"},
    "GOATS_FOOD"     : {"address": 0x19, "pretty_name": "Goat`s Food"},
    "HARP_STRING"    : {"address": 0x1A, "pretty_name": "Harp String"},
    "PASS"           : {"address": 0x1B, "pretty_name": "Pass"},
    "DREAM_ROD"      : {"address": 0x1C, "pretty_name": "Dream Rod"},
    "LEOS_BRUSH"     : {"address": 0x1D, "pretty_name": "Leo`s Brush"},
    "GREENWOOD_LEAF" : {"address": 0x1E, "pretty_name": "Greenwood Leaf"},
    "MOLES_RIBBON"   : {"address": 0x1F, "pretty_name": "Mole`s Ribbon"},
    "BIG_PEARL"      : {"address": 0x20, "pretty_name": "Big Pearl"},
    "MERMAIDS_TEARS" : {"address": 0x21, "pretty_name": "Mermaid`s Tears"},
    "MUSHROOM_SHOES" : {"address": 0x22, "pretty_name": "Mushroom Shoes"},
    "MOBILE_KEY"     : {"address": 0x23, "pretty_name": "Mobile Key"},
    "THUNDER_RING"   : {"address": 0x24, "pretty_name": "Thunder Ring"},
    "DELICIOUS_SEEDS": {"address": 0x25, "pretty_name": "Delicious Seeds"},
    "ACTINIDIA_LEAF" : {"address": 0x26, "pretty_name": "Actinidia Leaf"},
    "DOOR_KEY"       : {"address": 0x27, "pretty_name": "Door Key"},
    "PLATINUM_CARD"  : {"address": 0x28, "pretty_name": "Platinum Card"},
    "VIP_CARD"       : {"address": 0x29, "pretty_name": "VIP Card"},
    "EMBLEM_A"       : {"address": 0x2A, "pretty_name": "Emblem A"},
    "EMBLEM_B"       : {"address": 0x2B, "pretty_name": "Emblem B"},
    "EMBLEM_C"       : {"address": 0x2C, "pretty_name": "Emblem C"},
    "EMBLEM_D"       : {"address": 0x2D, "pretty_name": "Emblem D"},
    "EMBLEM_E"       : {"address": 0x2E, "pretty_name": "Emblem E"},
    "EMBLEM_F"       : {"address": 0x2F, "pretty_name": "Emblem F"},
    "EMBLEM_G"       : {"address": 0x30, "pretty_name": "Emblem G"},
    "EMBLEM_H"       : {"address": 0x31, "pretty_name": "Emblem H"},
    "RED_HOT_MIRROR" : {"address": 0x32, "pretty_name": "Red-Hot Mirror"},
    "RED_HOT_BALL"   : {"address": 0x33, "pretty_name": "Red-Hot Ball"},
    "RED_HOT_STICK"  : {"address": 0x34, "pretty_name": "Red-Hot Stick"},
    "POWER_BRACELET" : {"address": 0x35, "pretty_name": "Power Bracelet"},
    "SHIELD_BRACELET": {"address": 0x36, "pretty_name": "Shield Bracelet"},
    "SUPER_BRACELET" : {"address": 0x37, "pretty_name": "Super Bracelet"},
    "MEDICAL_HERB"   : {"address": 0x38, "pretty_name": "Medical Herb"},
    "STRANGE_BOTTLE" : {"address": 0x39, "pretty_name": "Strange Bottle"},
    "BROWN_STONE"    : {"address": 0x3A, "pretty_name": "Brown Stone"},
    "GREEN_STONE"    : {"address": 0x3B, "pretty_name": "Green Stone"},
    "BLUE_STONE"     : {"address": 0x3C, "pretty_name": "Blue Stone"},
    "SILVER_STONE"   : {"address": 0x3D, "pretty_name": "Silver Stone"},
    "PURPLE_STONE"   : {"address": 0x3E, "pretty_name": "Purple Stone"},
    "BLACK_STONE"    : {"address": 0x3F, "pretty_name": "Black Stone"},
    "MAGIC_BELL"     : {"address": 0x40, "pretty_name": "Magic Bell"},
    "GEMS_EXP"       : {"address": 0xFF}
 }
